;;; coffee-mode --- Emacs Major Mode for CoffeeScript
;;; https://github.com/defunkt/coffee-mode
(use-package coffee-mode
  :ensure t
  :mode (("\\.coffee.erb\\'" . coffee-mode))
  :config
  (setq coffee-tab-width 2)
  ;; remove the "Generated by CoffeeScript" header
  (add-to-list 'coffee-args-compile "--no-header"))


;;; json-mode --- Major mode for editing JSON files with emacs
;;; https://github.com/joshwnj/json-mode
(use-package json-mode
  :ensure t
  :defer t)

;;; js2-mode --- Improved JavaScript editing mode
;;; https://github.com/mooz/js2-mode
(use-package js2-mode
  :ensure t
  :mode "\\.js\\'"
  :config
  (add-hook 'js2-mode-hook 'js2-imenu-extras-mode)
  (add-hook 'js2-mode-hook (lambda () (electric-indent-local-mode -1)))
  (add-hook 'js2-mode-hook (lambda () (electric-indent-mode -1)))
  (add-hook 'js2-mode-hook (lambda () (electric-layout-mode -1)))
  (setq-default js-indent-level 2)
  (setq-default js-auto-indent-flag nil)
  (setq-default js2-mode-show-parse-errors nil)
  (setq-default js2-mode-show-strict-warnings nil)
  (setq-default js2-strict-missing-semi-warning nil)
  (setq-default js2-autoinsert-semi-and-warn nil))

(use-package skewer-mode
  :ensure t
  :defer t
  :init
  (add-hook 'js2-mode-hook 'skewer-mode))


;;; xref-js2 --- Jump to references/definitions using ag & js2-mode's AST in Emacs
;;; https://github.com/nicolaspetton/xref-js2
(use-package xref-js2
  :ensure t
  :defer t
  :config
  (add-hook 'js2-mode-hook (lambda ()
                             (add-hook 'xref-backend-functions #'xref-js2-xref-backend nil t)))
  )

;;; js2-refactor --- A JavaScript refactoring library for emacs
;;; https://github.com/magnars/js2-refactor.el
(use-package js2-refactor
  :ensure t
  :init
  (add-hook 'js2-mode-hook 'js2-refactor-mode)
  :bind (:map js2-mode-map
              ("C-k" . js2r-kill))
  )

(use-package company-tern
  :ensure t
  :defer t
  :init
  ;; (add-to-list 'company-backends 'company-tern)
  (add-hook 'js2-mode-hook (lambda () (tern-mode)))

  :config
  ;; Disable completion keybindings, as we use xref-js2 instead
  (define-key tern-mode-keymap (kbd "M-.") nil)
  (define-key tern-mode-keymap (kbd "M-,") nil)
  )

;;; indium --- A JavaScript development environment for Emacs
;;; https://indium.readthedocs.io/en/latest/setup.html
(use-package indium
  :ensure t
  :init
  (add-hook 'js-mode-hook 'indium-interaction-mode))

;;; rjsx-mode --- Emacs major modes for various Git configuration files
;;; https://github.com/felipeochoa/rjsx-mode
(use-package rjsx-mode
  :ensure t
  :mode "\\.jsx\\'"
  :config
  (add-to-list 'auto-mode-alist '("components\\/.*\\.jsx\\'" . rjsx-mode)))

;; References
;; https://emacs.cafe/emacs/javascript/setup/2017/04/23/emacs-setup-javascript.html
;; https://emacs.cafe/emacs/javascript/setup/2017/05/09/emacs-setup-javascript-2.html
